export type VendorDoc = Document & {
	webkitExitFullscreen?: () => void;
	msExitFullscreen?: () => void;

	webkitFullscreenElement?: Element | null;
	msFullscreenElement?: Element | null;
};

export type VendorEl = HTMLElement & {
	requestFullscreen?(): Promise<void>;
	webkitRequestFullscreen?(): Promise<void>;
	msRequestFullscreen?(): Promise<void>;
};

export interface Format {
	format_id: string;
	format_note: string;
	ext: string;
	vcodec: string;
	acodec: string;
	url: string;
	width?: number;
	height?: number;
	fps?: number;
	resolution?: string;
	filesize_in_bytes?: number;
};

export interface Stream {
	id: string;
	content: string;
	resolution: string;
	itag: number;
	bitrate: number;
	width: number;
	height: number;
	fps: number;
	quality: string;
	codec: string;
	videoOnly: boolean;
	format: string;
	url: string;
}

export interface Thumbnail {
	url: string;
	height: number;
	width: number;
	estimatedResolutionLevel: string;
}

export interface Description {
	content: string;
	type: number;
}

export interface Avatar {
	url: string;
	height: number;
	width: number;
	estimatedResolutionLevel: string;
}

export interface RelatedItem {
	id: string;
	infoType: string;
	url: string;
	name: string;
	thumbnails: Thumbnail[];
	streamType: string;
	uploaderName: string;
	textualUploadDate: string;
	viewCount: number;
	duration: number;
	uploaderUrl: string;
	uploaderAvatars: Avatar[];
	uploaderSubscriberCount: number;
	shortFormContent: boolean;
}

export interface Subtitle {
	id: string;
	content: string;
	format: string;
	locale: string;
	autogenerated: boolean;
	displayLanguageName: string;
	languageTag: string;
	formatId: number;
	url: string;
}

export interface StreamSegment {
	title: string;
	startTimeSeconds: number;
	url: string;
}

export interface Video {
	id: string;
	url: string;
	name: string;
	streamDate: string;
	thumbnails: Thumbnail[];
	textualUploadDate: string;
	duration: number;
	description: Description;
	viewCount: number;
	likeCount: number;
	dislikeCount: number;
	uploaderName: string;
	uploaderAvatars: Avatar[];
	uploaderSubscriberCount: number;
	videoStreams: Stream[];
	audioStreams: Stream[];
	videoOnlyStreams: Stream[];
	relatedItems: RelatedItem[];
	subtitles: Subtitle[];
	category: string;
	streamSegments: StreamSegment[];
	shortFormContent: boolean;

};

export type SearchResult = Video[];
