export type VendorDoc = Document & {
	webkitExitFullscreen?: () => void;
	msExitFullscreen?: () => void;

	webkitFullscreenElement?: Element | null;
	msFullscreenElement?: Element | null;
};

export type VendorEl = HTMLElement & {
	requestFullscreen?(): Promise<void>;
	webkitRequestFullscreen?(): Promise<void>;
	msRequestFullscreen?(): Promise<void>;
};

export interface Format {
	format_id: string;
	format_note: string;
	ext: string;
	vcodec: string;
	acodec: string;
	url: string;
	width?: number;
	height?: number;
	fps?: number;
	resolution?: string;
	filesize_in_bytes?: number;
};

export interface ItagItem {
	mediaFormat: string;
	id: number;
	itagType: string;
	avgBitrate: number;
	sampleRate?: number;
	audioChannels?: number;
	resolutionString?: string;
	fps: number;
	bitrate: number;
	width?: number;
	height?: number;
	initStart: number;
	initEnd: number;
	indexStart: number;
	indexEnd: number;
	quality?: string;
	codec: string;
	targetDurationSec: number;
	approxDurationMs: number;
	contentLength: number;
	audioTrackId?: string;
	audioTrackName?: string;
	audioLocale?: string;
	averageBitrate: number;
}

export interface Details {
	uploaderAvatars: Avatar[];
	videoTitle: string;
	description: {
		content: string;
	};
	uploadDate: string;
	channelSubscriberCount: number;
	dislikeCount: number;
	likeCount: number;
	viewCount: number;
	channelName: string;
}

export interface Stream {
	id: string;
	content: string;
	resolution: string;
	itag: number;
	bitrate: number;
	width: number;
	height: number;
	fps: number;
	quality: string;
	codec: string;
	itagItem: ItagItem;
	videoOnly: boolean;
	format: string;
	url: string;
}

export interface Subtitle {
	id: string;
	url: string;
	format: string;
	locale: string;  
	displayLanguageName: string;
	languageTag: string;
	autogenerated: boolean;
}

export interface Thumbnail {
	url: string;
	height: number;
	width: number;
	estimatedResolutionLevel: string;
}

export interface Description {
	content: string;
	type: number;
}

export interface Avatar {
	url: string;
	height: number;
	width: number;
	estimatedResolutionLevel: string;
}

export interface RelatedItem {
	id: string;
	infoType: string;
	url: string;
	name: string;
	thumbnails: Thumbnail[];
	streamType: string;
	uploaderName: string;
	textualUploadDate: string;
	viewCount: number;
	duration: number;
	uploaderUrl: string;
	uploaderAvatars: Avatar[];
	uploaderSubscriberCount: number;
	shortFormContent: boolean;
}

export interface Subtitle {
	id: string;
	content: string;
	format: string;
	locale: string;
	autogenerated: boolean;
	displayLanguageName: string;
	languageTag: string;
	formatId: number;
	url: string;
}

export interface StreamSegment {
	title: string;
	startTimeSeconds: number;
	url: string;
}

export interface Video {
	id: string;
	url: string;
	name: string;
	streamDate: string;
	thumbnails: Thumbnail[];
	textualUploadDate: string;
	duration: number;
	description: Description;
	viewCount: number;
	likeCount: number;
	dislikeCount: number;
	uploaderName: string;
	uploaderAvatars: Avatar[];
	uploaderSubscriberCount: number;
	videoStreams: Stream[];
	audioStreams: Stream[];
	videoOnlyStreams: Stream[];
	relatedItems: RelatedItem[];
	subtitles: Subtitle[];
	category: string;
	streamSegments: StreamSegment[];
	shortFormContent: boolean;

};

export interface SearchResult {
	url?: string;
	originalUrl?: string;
	name?: string;
	searchString: string;
	searchSuggestion?: string | null;
	isCorrectedSearch?: boolean;
	items: SearchItem[];
	nextPageUrl?: string;
	hasNextPage?: boolean;
}


export interface SearchItem {
	type: string;
	name: string;
	url: string;
	thumbnailUrl: string;
	uploaderName?: string;
	uploaderUrl?: string;
	uploaderAvatarUrl?: string;
	uploaderVerified?: boolean;
	duration?: number;
	viewCount?: number;
	uploadDate?: string;
	streamType?: string;
	isShortFormContent?: boolean;
	subscriberCount?: number;
	streamCount?: number;
	description?: string;
	playlistType?: string;
	videoCount?: number;
}

export interface PlayerConfiguration {
	streaming?: {
		bufferingGoal?: number;
		rebufferingGoal?: number;
		bufferBehind?: number;
	};
	drm?: Record<string, unknown>;
	manifest?: Record<string, unknown>;
}

export interface UIConfiguration {
	overflowMenuButtons?: string[];
	seekBarColors?: {
		base?: string;
		buffered?: string;
		played?: string;
	};
	controlPanelElements?: string[];
	addSeekBar?: boolean;
	addBigPlayButton?: boolean;
}

export interface ErrorEvent extends Event {
	detail: ShakaError;
}

export interface ShakaError {
	code: number;
	message: string;
	severity: number;
	category: number;
	data: unknown[];
}

export interface ShakaPlayerConfiguration {
	streaming?: {
		bufferingGoal?: number;
		rebufferingGoal?: number;
		bufferBehind?: number;
	};
	drm?: Record<string, unknown>;
	manifest?: Record<string, unknown>;
}

export interface ShakaUIConfiguration {
	overflowMenuButtons?: string[];
	seekBarColors?: {
		base?: string;
		buffered?: string;
		played?: string;
	};
	controlPanelElements?: string[];
	addSeekBar?: boolean;
	addBigPlayButton?: boolean;
}

export interface ShakaErrorEvent extends Event {
	detail: ShakaError;
}

export interface ShakaPlayerClass {
	new(video?: HTMLMediaElement): ShakaPlayerInstance;
	isBrowserSupported(): boolean;
}

export interface ShakaPlayerInstance {
	attach(video: HTMLMediaElement): Promise<void>;
	load(manifestUri: string, startTime?: number, mimeType?: string): Promise<void>;
	configure(config: ShakaPlayerConfiguration): void;
	destroy(): Promise<void>;
	addEventListener(type: string, listener: (event: ShakaErrorEvent) => void): void;
	removeEventListener(type: string, listener: (event: ShakaErrorEvent) => void): void;
}

export interface ShakaUIOverlayClass {
	new(player: ShakaPlayerInstance, videoContainer: HTMLElement, video: HTMLMediaElement): ShakaUIOverlayInstance;
}

export interface ShakaUIOverlayInstance {
	configure(config: ShakaUIConfiguration): void;
	destroy(): Promise<void>;
}

export interface ShakaPolyfill {
	installAll(): void;
}
