/**
 * Test Suite: subtitleSelection.ts
 * 
 * Tests for subtitle filtering, deduplication, and prioritization logic
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
    logSelectedSubtitles,
    selectSubtitles,
    subtitleSelection,
} from './subtitleSelection';
import type { Subtitle } from '$lib/types';
import {
    createMockSubtitle,
    createMockMultiLanguageSubtitles,
    createMockSubtitlesWithMissingFields,
    createMockSubtitlesWithOriginalLanguage,
    createMockSubtitlesWithRegionalVariants,
    createMockSubtitlesWithAutoGenerated,
    createMockDuplicateSubtitles,
    createMockSubtitlesWithDifferentFormats
} from '../../tests/fixtures/mockSubtitleData';

// =============================================================================
// selectSubtitles() Tests
// =============================================================================

describe('selectSubtitles', () => {
	describe('basic functionality', () => {
		it('should return empty array for empty input', () => {
			const result = selectSubtitles([]);
			
			expect(result).toEqual([]);
		});

		it('should return empty array for null input', () => {
			const result = selectSubtitles(null);
			
			expect(result).toEqual([]);
		});

		it('should return empty array for undefined input', () => {
			const result = selectSubtitles(undefined);
			
			expect(result).toEqual([]);
		});

		it('should return single subtitle unchanged', () => {
			const subtitle = createMockSubtitle();
			
			const result = selectSubtitles([subtitle]);
			
			expect(result).toHaveLength(1);
			expect(result[0]).toEqual(subtitle);
		});

		it('should handle multiple subtitles', () => {
			const subtitles = createMockMultiLanguageSubtitles();
			
			const result = selectSubtitles(subtitles);
			
			expect(result.length).toBeGreaterThan(0);
			expect(result.length).toBeLessThanOrEqual(subtitles.length);
		});
	});

	describe('format filtering', () => {
		it('should prefer VTT format when available', () => {
			const subtitles = createMockSubtitlesWithDifferentFormats();
			
			const result = selectSubtitles(subtitles);
			
			// Should only have VTT format
			expect(result.every(s => s.format === 'vtt')).toBe(true);
			expect(result.length).toBe(1); // Only English VTT
		});

		it('should fall back to srv3 when VTT not available', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					displayLanguageName: 'English',
					format: 'srv3',
					autogenerated: false
				}),
				createMockSubtitle({
					locale: 'es',
					displayLanguageName: 'Spanish',
					format: 'ttml',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should prefer srv3
			expect(result.every(s => s.format === 'srv3')).toBe(true);
		});

		it('should fall back to srv2 when VTT and srv3 not available', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					format: 'srv2',
					autogenerated: false
				}),
				createMockSubtitle({
					locale: 'es',
					format: 'ttml',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			expect(result.every(s => s.format === 'srv2')).toBe(true);
		});

		it('should fall back to any format when no preferred format available', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					format: 'unknown',
					autogenerated: false
				}),
				createMockSubtitle({
					locale: 'es',
					format: 'custom',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should return all subtitles when no preferred format found
			expect(result.length).toBe(2);
		});

		it('should handle case-insensitive format matching', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					format: 'VTT',
					autogenerated: false
				}),
				createMockSubtitle({
					locale: 'es',
					format: 'Vtt',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			expect(result.length).toBe(2);
			expect(result.every(s => s.format?.toLowerCase() === 'vtt')).toBe(true);
		});
	});

	describe('deduplication', () => {
		it('should remove duplicate language subtitles', () => {
			const subtitles = createMockDuplicateSubtitles();
			
			const result = selectSubtitles(subtitles);
			
			// Should only have one English subtitle
			expect(result.length).toBe(1);
			expect(result[0].locale).toBe('en');
		});

		it('should prefer manual over auto-generated when deduplicating', () => {
			const subtitles = createMockSubtitlesWithAutoGenerated();
			
			const result = selectSubtitles(subtitles);
			
			// Should have 2 subtitles (one per language)
			expect(result.length).toBe(2);
			
			// Both should be manual
			expect(result.every(s => !s.autogenerated)).toBe(true);
		});

		it('should keep auto-generated if no manual available', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					displayLanguageName: 'English (auto)',
					autogenerated: true
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			expect(result.length).toBe(1);
			expect(result[0].autogenerated).toBe(true);
		});

		it('should handle regional variants as separate languages', () => {
			const subtitles = createMockSubtitlesWithRegionalVariants();
			
			const result = selectSubtitles(subtitles);
			
			// Each regional variant should be kept separate
			expect(result.length).toBe(4);
		});

		it('should normalize language codes for deduplication', () => {
			const subtitles = [
				createMockSubtitle({
					id: 'es-1',
					locale: 'es_419',
					languageTag: 'es-419',
					displayLanguageName: 'Spanish (Latin America)',
					autogenerated: false
				}),
				createMockSubtitle({
					id: 'es-2',
					locale: 'es-419',
					languageTag: 'es-419',
					displayLanguageName: 'Spanish (Latin America)',
					autogenerated: true
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should deduplicate despite underscore vs hyphen
			expect(result.length).toBe(1);
			expect(result[0].autogenerated).toBe(false);
		});
	});

	describe('language priority sorting', () => {
		it('should sort undefined/original language first', () => {
			const subtitles = createMockSubtitlesWithOriginalLanguage();
			
			const result = selectSubtitles(subtitles);
			
			// Original/undefined should be first
			expect(result[0].locale).toBe('und');
		});

		it('should sort English second (after original)', () => {
			const subtitles = createMockSubtitlesWithOriginalLanguage();
			
			const result = selectSubtitles(subtitles);
			
			// English should be second
			expect(result[1].locale).toBe('en');
		});

		it('should sort other languages alphabetically', () => {
			const subtitles = [
				createMockSubtitle({ locale: 'fr', displayLanguageName: 'French' }),
				createMockSubtitle({ locale: 'de', displayLanguageName: 'German' }),
				createMockSubtitle({ locale: 'es', displayLanguageName: 'Spanish' }),
				createMockSubtitle({ locale: 'en', displayLanguageName: 'English' })
			];
			
			const result = selectSubtitles(subtitles);
			
			// English first, then alphabetically
			expect(result[0].locale).toBe('en');
			expect(result[1].locale).toBe('de'); // German
			expect(result[2].locale).toBe('es'); // Spanish
			expect(result[3].locale).toBe('fr'); // French
		});

		it('should prefer manual over auto when same language and priority', () => {
			const subtitles = [
				createMockSubtitle({
					id: 'es-auto',
					locale: 'es',
					displayLanguageName: 'Spanish (auto)',
					autogenerated: true
				}),
				createMockSubtitle({
					id: 'es-manual',
					locale: 'es',
					displayLanguageName: 'Spanish',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should only have manual (deduplication)
			expect(result.length).toBe(1);
			expect(result[0].autogenerated).toBe(false);
		});
	});

	describe('missing or malformed data', () => {
		it('should handle missing locale field', () => {
			const subtitles = createMockSubtitlesWithMissingFields();
			
			const result = selectSubtitles(subtitles);
			
			// Should still process using languageTag
			expect(result.length).toBeGreaterThan(0);
		});

		it('should handle missing format field', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					format: undefined,
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should still return subtitle
			expect(result.length).toBe(1);
		});

		it('should handle empty locale and languageTag', () => {
			const subtitles = [
				createMockSubtitle({
					locale: '',
					languageTag: '',
					displayLanguageName: 'Unknown',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			expect(result.length).toBe(1);
		});

		it('should handle mixed valid and invalid subtitles', () => {
			const subtitles = [
				createMockSubtitle({ locale: 'en', displayLanguageName: 'English' }),
				createMockSubtitle({ locale: '', languageTag: '', displayLanguageName: 'Unknown' }),
				createMockSubtitle({ locale: 'es', displayLanguageName: 'Spanish' })
			];
			
			const result = selectSubtitles(subtitles);
			
			expect(result.length).toBeGreaterThan(0);
		});
	});

	describe('complex scenarios', () => {
		it('should handle mix of formats, duplicates, and priorities', () => {
			const subtitles = [
				// English - VTT - manual
				createMockSubtitle({
					id: 'en-vtt-manual',
					locale: 'en',
					displayLanguageName: 'English',
					format: 'vtt',
					autogenerated: false
				}),
				// English - VTT - auto
				createMockSubtitle({
					id: 'en-vtt-auto',
					locale: 'en',
					displayLanguageName: 'English (auto)',
					format: 'vtt',
					autogenerated: true
				}),
				// Spanish - VTT
				createMockSubtitle({
					id: 'es-vtt',
					locale: 'es',
					displayLanguageName: 'Spanish',
					format: 'vtt',
					autogenerated: false
				}),
				// French - TTML (non-preferred format)
				createMockSubtitle({
					id: 'fr-ttml',
					locale: 'fr',
					displayLanguageName: 'French',
					format: 'ttml',
					autogenerated: false
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should prefer VTT format
			expect(result.every(s => s.format === 'vtt')).toBe(true);
			
			// Should have 2 subtitles (English and Spanish, French filtered out)
			expect(result.length).toBe(2);
			
			// Should prefer manual over auto
			const english = result.find(s => s.locale === 'en');
			expect(english?.autogenerated).toBe(false);
			
			// English should be first
			expect(result[0].locale).toBe('en');
		});

		it('should handle real-world YouTube subtitle scenario', () => {
			const subtitles = [
				// Original language (undefined)
				createMockSubtitle({
					locale: 'und',
					languageTag: 'original',
					displayLanguageName: 'Original',
					format: 'vtt',
					autogenerated: false
				}),
				// English - manual
				createMockSubtitle({
					locale: 'en',
					displayLanguageName: 'English',
					format: 'vtt',
					autogenerated: false
				}),
				// English - auto-generated
				createMockSubtitle({
					locale: 'en',
					displayLanguageName: 'English (auto-generated)',
					format: 'vtt',
					autogenerated: true
				}),
				// Spanish - manual
				createMockSubtitle({
					locale: 'es',
					displayLanguageName: 'Spanish',
					format: 'vtt',
					autogenerated: false
				}),
				// French - auto
				createMockSubtitle({
					locale: 'fr',
					displayLanguageName: 'French (auto-generated)',
					format: 'vtt',
					autogenerated: true
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			// Should have 4 subtitles (original, en, es, fr)
			expect(result.length).toBe(4);
			
			// Check order: original -> en -> es -> fr
			expect(result[0].locale).toBe('und');
			expect(result[1].locale).toBe('en');
			expect(result[2].locale).toBe('es');
			expect(result[3].locale).toBe('fr');
			
			// English should be manual
			expect(result[1].autogenerated).toBe(false);
			
			// French should be auto (no manual available)
			expect(result[3].autogenerated).toBe(true);
		});
	});

	describe('edge cases', () => {
		it('should handle very large subtitle arrays', () => {
			const subtitles: Subtitle[] = [];
			for (let i = 0; i < 100; i++) {
				subtitles.push(createMockSubtitle({
					id: `sub-${i}`,
					locale: `lang-${i % 10}`,
					displayLanguageName: `Language ${i}`,
					autogenerated: i % 2 === 0
				}));
			}
			
			const result = selectSubtitles(subtitles);
			
			// Should deduplicate to ~10 languages
			expect(result.length).toBeLessThanOrEqual(10);
		});

		it('should handle all auto-generated subtitles', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					displayLanguageName: 'English (auto)',
					autogenerated: true
				}),
				createMockSubtitle({
					locale: 'es',
					displayLanguageName: 'Spanish (auto)',
					autogenerated: true
				})
			];
			
			const result = selectSubtitles(subtitles);
			
			expect(result.length).toBe(2);
			expect(result.every(s => s.autogenerated)).toBe(true);
		});

		it('should handle all manual subtitles', () => {
			const subtitles = createMockMultiLanguageSubtitles();
			
			const result = selectSubtitles(subtitles);
			
			expect(result.every(s => !s.autogenerated)).toBe(true);
		});

		it('should handle subtitles with identical properties', () => {
			const subtitle = createMockSubtitle();
			const subtitles = [subtitle, { ...subtitle }, { ...subtitle }];
			
			const result = selectSubtitles(subtitles);
			
			// Should deduplicate to one
			expect(result.length).toBe(1);
		});
	});
});

// =============================================================================
// logSelectedSubtitles() Tests
// =============================================================================

describe('logSelectedSubtitles', () => {
	beforeEach(() => {
		// Mock console methods
		vi.spyOn(console, 'log').mockImplementation(() => {});
	});

	describe('basic logging', () => {
		it('should log message for empty subtitle array', () => {
			logSelectedSubtitles([]);
			
			expect(console.log).toHaveBeenCalledWith('No subtitles available');
		});

		it('should log subtitle count', () => {
			const subtitles = createMockMultiLanguageSubtitles();
			
			logSelectedSubtitles(subtitles);
			
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining(`Selected ${subtitles.length} subtitle tracks`)
			);
		});

		it('should log individual subtitle information', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'en',
					displayLanguageName: 'English',
					format: 'vtt',
					autogenerated: false
				})
			];
			
			logSelectedSubtitles(subtitles);
			
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('English')
			);
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('en')
			);
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('vtt')
			);
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('manual')
			);
		});
	});

	describe('subtitle type labeling', () => {
		it('should label manual subtitles as "manual"', () => {
			const subtitles = [
				createMockSubtitle({
					displayLanguageName: 'English',
					autogenerated: false
				})
			];
			
			logSelectedSubtitles(subtitles);
			
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('[manual]')
			);
		});

		it('should label auto-generated subtitles as "auto"', () => {
			const subtitles = [
				createMockSubtitle({
					displayLanguageName: 'English',
					autogenerated: true
				})
			];
			
			logSelectedSubtitles(subtitles);
			
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('[auto]')
			);
		});
	});

	describe('multiple subtitles', () => {
		it('should log all subtitles', () => {
			const subtitles = createMockMultiLanguageSubtitles();
			
			logSelectedSubtitles(subtitles);
			
			// Should log header + each subtitle
			expect(console.log).toHaveBeenCalledTimes(subtitles.length + 1);
		});

		it('should number subtitles correctly', () => {
			const subtitles = createMockMultiLanguageSubtitles();
			
			logSelectedSubtitles(subtitles);
			
			// Check for numbering
			expect(console.log).toHaveBeenCalledWith(expect.stringContaining('1.'));
			expect(console.log).toHaveBeenCalledWith(expect.stringContaining('2.'));
		});
	});

	describe('language code display', () => {
		it('should display normalized language codes', () => {
			const subtitles = [
				createMockSubtitle({
					locale: 'es_419',
					languageTag: 'es-419',
					displayLanguageName: 'Spanish (Latin America)'
				})
			];
			
			logSelectedSubtitles(subtitles);
			
			// Should normalize to es-419
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('es-419')
			);
		});

		it('should handle missing locale', () => {
			const subtitles = [
				createMockSubtitle({
					locale: undefined,
					languageTag: 'en',
					displayLanguageName: 'English'
				})
			];
			
			logSelectedSubtitles(subtitles);
			
			// Should use languageTag as fallback
			expect(console.log).toHaveBeenCalledWith(
				expect.stringContaining('en')
			);
		});
	});
});