import { extractLanguageInfo } from '$lib/utils/languageUtils';
import type { Stream, Subtitle } from '$lib/types';
import { normalizeLanguageCode, getLanguageName } from '$lib/utils/languageUtils';
import { extractByteRanges } from '$lib/utils/streamSelection';
import { DEFAULT_VIDEO, DEFAULT_AUDIO, SUBTITLE_MIME_TYPES } from './constants';
import type { VideoStreamConfig, AudioStreamConfig, SubtitleStreamConfig, VideoPlayerConfig } from './types';


/**
 * Adapts a single video stream to player configuration format
 */
function adaptVideoStream(stream: Stream): VideoStreamConfig {
	return {
		url: stream.url,
		codec: stream.codec || DEFAULT_VIDEO.CODEC,
		mimeType: DEFAULT_VIDEO.MIME_TYPE,
		width: stream.width || DEFAULT_VIDEO.WIDTH,
		height: stream.height || DEFAULT_VIDEO.HEIGHT,
		bandwidth: stream.bitrate || DEFAULT_VIDEO.BANDWIDTH,
		frameRate: stream.fps || DEFAULT_VIDEO.FRAME_RATE,
		format: stream.format || DEFAULT_VIDEO.FORMAT,
		...extractByteRanges(stream.itagItem)
	};
}
/**
 * Adapts a single audio stream to player configuration format
 */
function adaptAudioStream(stream: Stream): AudioStreamConfig {
	const language = extractLanguageInfo(stream);
	const itagItem = stream.itagItem;

	return {
		url: stream.url,
		codec: stream.codec || DEFAULT_AUDIO.CODEC,
		mimeType: DEFAULT_AUDIO.MIME_TYPE,
		bandwidth: stream.bitrate || DEFAULT_AUDIO.BANDWIDTH,
		sampleRate: itagItem?.sampleRate || DEFAULT_AUDIO.SAMPLE_RATE,
		channels: itagItem?.audioChannels || DEFAULT_AUDIO.CHANNELS,
		format: stream.format || DEFAULT_AUDIO.FORMAT,
		language: language.code,
		languageName: language.name,
		...extractByteRanges(itagItem)
	};
}
/**
 * Adapts a single subtitle to player configuration format
 */
function adaptSubtitleStream(subtitle: Subtitle): SubtitleStreamConfig {
	const language = normalizeLanguageCode(subtitle.locale || subtitle.languageTag);
	const format = subtitle.format?.toLowerCase() || 'vtt';

	return {
		url: subtitle.url,
		language,
		languageName: subtitle.displayLanguageName || getLanguageName(language),
		format,
		mimeType: SUBTITLE_MIME_TYPES[format] || 'text/vtt',
		kind: subtitle.autogenerated ? 'captions' : 'subtitles',
		isAutoGenerated: subtitle.autogenerated
	};
}
/**
 * Adapt video and audio streams into player configuration
 */

export function adaptPlayerConfig(
	videoStreams: Stream[] | undefined,
	audioStreams: Stream[] | undefined,
	subtitles: Subtitle[] | undefined,
	duration: number,
	posterUrl: string
): VideoPlayerConfig {
	return {
		videoStream: videoStreams?.length
			? videoStreams.map(adaptVideoStream)
			: null,
		audioStream: audioStreams?.length
			? audioStreams.map(adaptAudioStream)
			: null,
		subtitleStream: subtitles?.length
			? subtitles.map(adaptSubtitleStream)
			: null,
		duration,
		poster: posterUrl
	};
}
