
/**
 * Video stream configuration for the player
 */
export interface VideoStreamConfig {
	url: string;
	codec: string;
	mimeType: string;
	width: number;
	height: number;
	bandwidth: number;
	frameRate: number;
	format: string;
	initStart?: number;
	initEnd?: number;
	indexStart?: number;
	indexEnd?: number;
}

/**
 * Audio stream configuration for the player
 */
export interface AudioStreamConfig {
	url: string;
	codec: string;
	mimeType: string;
	bandwidth: number;
	sampleRate: number;
	channels: number;
	format: string;
	language: string;
	languageName: string;
	initStart?: number;
	initEnd?: number;
	indexStart?: number;
	indexEnd?: number;
}

/**
 * Subtitle stream configuration for the player
 */
export interface SubtitleStreamConfig {
	url: string;
	language: string;
	languageName: string;
	format: string;
	mimeType: string;
	kind: 'subtitles' | 'captions';
	isAutoGenerated: boolean;
}
/**
 * Video player configuration derived from selected streams
 */
export interface VideoPlayerConfig {
	manifestUrl: string;
	duration: number;
	poster: string;
}

/**
 * Video metadata adapted for display components
 */
export interface VideoMetadata {
	title: string;
	description: string;
	channelName: string;
	channelAvatar: string | null;
	viewCount: number;
	uploadDate: string;
	likeCount: number;
	dislikeCount: number;
	subscriberCount: number;
}

/**
 * Related video configuration for listings display
 */
export interface RelatedVideoConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	channelName: string;
	channelAvatar: string | null;
	viewCount: number;
	uploadDate: string;
	duration: number;
	channelId: string;
}

/**
 * Search result configuration for VideoResult component display
 */
export interface VideoSearchResultConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	channelName: string;
	channelUrl: string;
	channelAvatar: string;
	verified: boolean;
	viewCount: number;
	duration: number;
	uploadDate: string;
	type: "VIDEO_STREAM";
}

/**
 * Search result configuration for Channel result component display
 */
export interface ChannelSearchResultConfig {
	id: string;
	url?: string;
	name: string;
	avatar: string;
	verified: boolean;
	subscriberCount: number;
	streamCount?: number;
	description: string | null;
	type: "channel";
}

/**
 * Comments result configuration for Comments component display
 */
export interface CommentConfig {
	id: string;
	text: string;
	author: string;
	authorAvatar: string;
	authorUrl: string;
	isVerified: boolean;
	isChannelOwner: boolean;
	uploadDate: string;
	likeCount: number;
	likeCountText: string;
	isPinned: boolean;
	isHearted: boolean;
	replyCount: number;
	hasReplies: boolean;
	repliesUrl?: string;
}

/**
 * Channel result configuration
 */
export interface ChannelConfig {
	id: string;
	name: string;
	handle: string;
	avatarUrl: string | null;
	bannerUrl: string | null;
	description: string | null;
	subscriberCount: string; // formatted, e.g. "16.8M"
	videoCount: number; // from videos list length or a dedicated field if API provides it
	verified: boolean;
}

/**
 * Channel video result configuration
 */
export interface ChannelVideoConfig {
	id: string;
	title: string;
	thumbnail: string;
	uploaderName: string;
	uploaderUrl: string | null;
	uploadedDate: string;
	duration: number;
	viewCount: number;
	isShort: boolean;
}



