import type { Description } from '$lib/types';

/**
 * Subtitle stream configuration for the player
 */
export interface SubtitleStreamConfig {
	url: string;
	language: string;
	languageName: string;
	format: string;
	mimeType: string;
	kind: 'subtitles' | 'captions';
	isAutoGenerated: boolean;
}

/**
 * Video player configuration derived from selected streams
 */
export interface VideoPlayerConfig {
	manifestUrl: string;
	duration: number;
	poster: string;
	isMuxed?: boolean
}

/**
 * Video metadata adapted for display components
 */
export interface VideoMetadata {
	title: string;
	description: string;
	channelName: string;
	channelAvatar: string | null;
	viewCount: number;
	uploadDate: string;
	likeCount: number;
	dislikeCount: number;
	subscriberCount: number;
}

/**
 * Related video configuration for listings display
 */
export interface RelatedVideoConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	channelName: string;
	channelId: string;
	channelAvatar: string | null;
	viewCount: number;
	uploadDate: string;
	duration: number;
}

/**
 * Search result configuration for VideoResult component display
 */
export interface VideoSearchResultConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	channelName: string;
	channelUrl: string;
	channelAvatar: string;
	verified: boolean;
	viewCount: number;
	duration: number;
	uploadDate: string;
	description: string;
	type: "VIDEO_STREAM" | "stream";
}

/**
 * Playlist video result configuration
 */
export interface PlaylistSearchResultConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	uploaderName: string;
	uploaderUrl: string | null;
	videoCount: number;
	type: "playlist";
}

/**
 * Search result configuration for Channel result component display
 */
export interface ChannelSearchResultConfig {
	id: string;
	url?: string;
	name: string;
	avatar: string;
	verified: boolean;
	subscriberCount: number;
	streamCount?: number;
	description: string | null;
	type: "channel";
}

export type SearchResultConfig = VideoSearchResultConfig | ChannelSearchResultConfig | PlaylistSearchResultConfig;

/**
 * Comments result configuration for Comments component display
 */
export interface CommentConfig {
	id: string;
	text: string;
	author: string;
	authorAvatar: string;
	authorUrl: string;
	isVerified: boolean;
	isChannelOwner: boolean;
	uploadDate: string;
	likeCount: number;
	likeCountText: string;
	isPinned: boolean;
	isHearted: boolean;
	replyCount: number;
	hasReplies: boolean;
	repliesUrl?: string;
}

/**
 * Channel result configuration
 */
export interface ChannelConfig {
	id: string;
	name: string;
	handle: string;
	avatarUrl: string | null;
	bannerUrl: string | null;
	description: string | null;
	subscriberCount: string; // formatted, e.g. "16.8M"
	videoCount: number; // from videos list length or a dedicated field if API provides it
	verified: boolean;
}

/**
 * Channel video result configuration
 */
export interface ChannelVideoConfig {
	id: string;
	title: string;
	thumbnail: string;
	uploaderName: string;
	uploaderUrl: string | null;
	uploadedDate: string;
	duration: number;
	viewCount: number;
	isShort: boolean;
}

/**
 * Playlist info configuration
 */
export interface PlaylistInfoConfig {
	id: string;
	name: string;
	url: string;
	uploaderName: string;
	uploaderId: string;
	uploaderUrl: string | null;
	uploaderAvatarUrl: string | null;
	bannerUrl?: string | null;
	thumbnailUrl: string | null;
	description?: Description;
}




