
/**
 * Video stream configuration for the player
 */
export interface VideoStreamConfig {
	url: string;
	codec: string;
	mimeType: string;
	width: number;
	height: number;
	bandwidth: number;
	frameRate: number;
	format: string;
	initStart?: number;
	initEnd?: number;
	indexStart?: number;
	indexEnd?: number;
}

/**
 * Audio stream configuration for the player
 */
export interface AudioStreamConfig {
	url: string;
	codec: string;
	mimeType: string;
	bandwidth: number;
	sampleRate: number;
	channels: number;
	format: string;
	language: string;
	languageName: string;
	initStart?: number;
	initEnd?: number;
	indexStart?: number;
	indexEnd?: number;
}

/**
 * Subtitle stream configuration for the player
 */
export interface SubtitleStreamConfig {
	url: string;
	language: string;
	languageName: string;
	format: string;
	mimeType: string;
	kind: 'subtitles' | 'captions';
	isAutoGenerated: boolean;
}
/**
 * Video player configuration derived from selected streams
 */
export interface VideoPlayerConfig {
	manifestUrl: string;
	duration: number;
	poster: string;
}

/**
 * Video metadata adapted for display components
 */
export interface VideoMetadata {
	title: string;
	description: string;
	channelName: string;
	channelAvatar: string | null;
	viewCount: number;
	uploadDate: string;
	likeCount: number;
	dislikeCount: number;
	subscriberCount: number;
}

/**
 * Related video configuration for listings display
 */
export interface RelatedVideoConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	channelName: string;
	channelAvatar: string | null;
	viewCount: number;
	uploadDate: string;
	duration: number;
}

/**
 * Search result configuration for VideoResult component display
 * Add this to your existing adapters/types.ts file
 */
export interface SearchResultConfig {
	id: string;
	url: string;
	title: string;
	thumbnail: string;
	channelName: string;
	channelUrl: string;
	channelAvatar: string;
	verified: boolean;
	viewCount: number;
	duration: number;
	uploadDate: string;
	type: string;
}

