/**
 * Shared Test Fixtures for API Tests
 * 
 * Contains reusable mock data for API responses across all API test files
 */

import type { Stream, Subtitle, SearchResult, RelatedItem, SearchItem } from '$lib/types';

// =============================================================================
// Stream Fixtures
// =============================================================================

export const mockVideoStream: Stream = {
	id: 'video-stream-1',
	content: 'video/mp4',
	resolution: '1920x1080',
	itag: 137,
	bitrate: 5000000,
	width: 1920,
	height: 1080,
	fps: 30,
	quality: '1080p',
	codec: 'avc1.640028',
	itagItem: {
		mediaFormat: 'MPEG_4',
		id: 137,
		itagType: 'VIDEO',
		avgBitrate: 5000000,
		resolutionString: '1920x1080',
		fps: 30,
		bitrate: 5000000,
		width: 1920,
		height: 1080,
		initStart: 0,
		initEnd: 740,
		indexStart: 741,
		indexEnd: 2296,
		quality: '1080p',
		codec: 'avc1.640028',
		targetDurationSec: 5,
		approxDurationMs: 300000,
		contentLength: 50000000,
		averageBitrate: 5000000
	},
	videoOnly: true,
	format: 'MPEG_4',
	url: 'https://example.com/video/stream1'
};

export const mockAudioStream: Stream = {
	id: 'audio-stream-1',
	content: 'audio/mp4',
	resolution: '',
	itag: 140,
	bitrate: 128000,
	width: 0,
	height: 0,
	fps: 0,
	quality: 'medium',
	codec: 'mp4a.40.2',
	itagItem: {
		mediaFormat: 'M4A',
		id: 140,
		itagType: 'AUDIO',
		avgBitrate: 128000,
		sampleRate: 44100,
		audioChannels: 2,
		fps: 0,
		bitrate: 128000,
		initStart: 0,
		initEnd: 648,
		indexStart: 649,
		indexEnd: 1196,
		codec: 'mp4a.40.2',
		targetDurationSec: 5,
		approxDurationMs: 300000,
		contentLength: 5000000,
		averageBitrate: 128000
	},
	videoOnly: false,
	format: 'M4A',
	url: 'https://example.com/audio/stream1'
};



export const mockAudioStreamWithLanguage: Stream = {
	...mockAudioStream,
	id: 'audio-stream-2',
	itagItem: {
		...mockAudioStream.itagItem,
		audioTrackId: 'audio.en',
		audioTrackName: 'English',
		audioLocale: 'en'
	}
};

export const mockVideoStreams: Stream[] = [
	mockVideoStream,
	{
		...mockVideoStream,
		id: 'video-stream-2',
		itag: 136,
		resolution: '1280x720',
		width: 1280,
		height: 720,
		quality: '720p',
		bitrate: 2500000,
		url: 'https://example.com/video/stream2'
	},
	{
		...mockVideoStream,
		id: 'video-stream-3',
		itag: 135,
		resolution: '854x480',
		width: 854,
		height: 480,
		quality: '480p',
		bitrate: 1000000,
		url: 'https://example.com/video/stream3'
	}
];

// =============================================================================
// Subtitle Fixtures
// =============================================================================

export const mockSubtitle: Subtitle = {
    id: 'subtitle-1',
    url: 'https://example.com/subtitles/en.vtt',
    format: 'vtt',
    locale: 'en',
    displayLanguageName: 'English',
    languageTag: 'en',
    autogenerated: false,
    content: '',
    formatId: 0
};

export const mockSubtitles: Subtitle[] = [
	mockSubtitle,
	{
        id: 'subtitle-2',
        url: 'https://example.com/subtitles/es.vtt',
        format: 'vtt',
        locale: 'es',
        displayLanguageName: 'Spanish',
        languageTag: 'es',
        autogenerated: false,
        content: '',
        formatId: 0
    },
	{
        id: 'subtitle-3',
        url: 'https://example.com/subtitles/en-auto.vtt',
        format: 'vtt',
        locale: 'en',
        displayLanguageName: 'English (auto-generated)',
        languageTag: 'en',
        autogenerated: true,
        content: '',
        formatId: 0
    }
];