/**
 * Shared Test Fixtures for API Tests
 * 
 * Contains reusable mock data for API responses across all API test files
 */

import type { Details, Stream, Subtitle, SearchResult, RelatedItem } from '$lib/types';

// =============================================================================
// Video Details Fixtures
// =============================================================================

export const mockVideoDetails: Details = {
	uploaderAvatars: [
		{
			url: 'https://example.com/avatar.jpg',
			height: 48,
			width: 48,
			estimatedResolutionLevel: 'LOW'
		}
	],
	videoTitle: 'Test Video Title',
	description: {
		content: 'This is a test video description with details about the content.'
	},
	uploadDate: '2024-01-15',
	channelSubscriberCount: 1500000,
	dislikeCount: 100,
	likeCount: 50000,
	viewCount: 1000000,
	channelName: 'Test Channel'
};

export const mockVideoDetailsMinimal: Details = {
	uploaderAvatars: [],
	videoTitle: 'Minimal Video',
	description: {
		content: ''
	},
	uploadDate: '2024-01-01',
	channelSubscriberCount: 0,
	dislikeCount: 0,
	likeCount: 0,
	viewCount: 0,
	channelName: 'Unknown Channel'
};

// =============================================================================
// Stream Fixtures
// =============================================================================

export const mockVideoStream: Stream = {
	id: 'video-stream-1',
	content: 'video/mp4',
	resolution: '1920x1080',
	itag: 137,
	bitrate: 5000000,
	width: 1920,
	height: 1080,
	fps: 30,
	quality: '1080p',
	codec: 'avc1.640028',
	itagItem: {
		mediaFormat: 'MPEG_4',
		id: 137,
		itagType: 'VIDEO',
		avgBitrate: 5000000,
		resolutionString: '1920x1080',
		fps: 30,
		bitrate: 5000000,
		width: 1920,
		height: 1080,
		initStart: 0,
		initEnd: 740,
		indexStart: 741,
		indexEnd: 2296,
		quality: '1080p',
		codec: 'avc1.640028',
		targetDurationSec: 5,
		approxDurationMs: 300000,
		contentLength: 50000000,
		averageBitrate: 5000000
	},
	videoOnly: true,
	format: 'MPEG_4',
	url: 'https://example.com/video/stream1'
};

export const mockAudioStream: Stream = {
	id: 'audio-stream-1',
	content: 'audio/mp4',
	resolution: '',
	itag: 140,
	bitrate: 128000,
	width: 0,
	height: 0,
	fps: 0,
	quality: 'medium',
	codec: 'mp4a.40.2',
	itagItem: {
		mediaFormat: 'M4A',
		id: 140,
		itagType: 'AUDIO',
		avgBitrate: 128000,
		sampleRate: 44100,
		audioChannels: 2,
		fps: 0,
		bitrate: 128000,
		initStart: 0,
		initEnd: 648,
		indexStart: 649,
		indexEnd: 1196,
		codec: 'mp4a.40.2',
		targetDurationSec: 5,
		approxDurationMs: 300000,
		contentLength: 5000000,
		averageBitrate: 128000
	},
	videoOnly: false,
	format: 'M4A',
	url: 'https://example.com/audio/stream1'
};



export const mockAudioStreamWithLanguage: Stream = {
	...mockAudioStream,
	id: 'audio-stream-2',
	itagItem: {
		...mockAudioStream.itagItem,
		audioTrackId: 'audio.en',
		audioTrackName: 'English',
		audioLocale: 'en'
	}
};

export const mockVideoStreams: Stream[] = [
	mockVideoStream,
	{
		...mockVideoStream,
		id: 'video-stream-2',
		itag: 136,
		resolution: '1280x720',
		width: 1280,
		height: 720,
		quality: '720p',
		bitrate: 2500000,
		url: 'https://example.com/video/stream2'
	},
	{
		...mockVideoStream,
		id: 'video-stream-3',
		itag: 135,
		resolution: '854x480',
		width: 854,
		height: 480,
		quality: '480p',
		bitrate: 1000000,
		url: 'https://example.com/video/stream3'
	}
];

export const mockAudioStreams: Stream[] = [
	mockAudioStream,
	mockAudioStreamWithLanguage,
	{
		...mockAudioStream,
		id: 'audio-stream-3',
		itag: 139,
		bitrate: 48000,
		quality: 'low',
		url: 'https://example.com/audio/stream3'
	}
];

// =============================================================================
// Subtitle Fixtures
// =============================================================================

export const mockSubtitle: Subtitle = {
    id: 'subtitle-1',
    url: 'https://example.com/subtitles/en.vtt',
    format: 'vtt',
    locale: 'en',
    displayLanguageName: 'English',
    languageTag: 'en',
    autogenerated: false,
    content: '',
    formatId: 0
};

export const mockSubtitles: Subtitle[] = [
	mockSubtitle,
	{
        id: 'subtitle-2',
        url: 'https://example.com/subtitles/es.vtt',
        format: 'vtt',
        locale: 'es',
        displayLanguageName: 'Spanish',
        languageTag: 'es',
        autogenerated: false,
        content: '',
        formatId: 0
    },
	{
        id: 'subtitle-3',
        url: 'https://example.com/subtitles/en-auto.vtt',
        format: 'vtt',
        locale: 'en',
        displayLanguageName: 'English (auto-generated)',
        languageTag: 'en',
        autogenerated: true,
        content: '',
        formatId: 0
    }
];

// =============================================================================
// Related Stream Fixtures
// =============================================================================

export const mockRelatedStream: RelatedItem = {
	id: 'related-stream-1',
    infoType: 'STREAM',
    url: 'https://example.com/watch?v=related1',
    name: 'Related Video 1',
    thumbnails: [
        {
            url: 'https://example.com/thumbs/related1_low.jpg',
            height: 94,
            width: 168,
            estimatedResolutionLevel: 'LOW'
        },
        {
            url: 'https://example.com/thumbs/related1_medium.jpg',
            height: 188,
            width: 336,
            estimatedResolutionLevel: 'MEDIUM'
        }
    ],
    streamType: 'VIDEO_STREAM',
    uploaderName: 'Related Channel 1',
    textualUploadDate: '4 years ago',
    viewCount: 64000000,
    duration: 973,
    uploaderUrl: 'https://example.com/channel/related1',
    uploaderAvatars: [
        {
            url: 'https://example.com/avatars/related1.jpg',
            height: 68,
            width: 68,
            estimatedResolutionLevel: 'LOW'
        }
    ],
    uploaderSubscriberCount: 0,
    shortFormContent: false	
};

export const mockRelatedStreams: RelatedItem[] = [
	mockRelatedStream,
	{
		...mockRelatedStream,
		id: 'related-stream-2',
		url: 'https://example.com/watch?v=related2',
		name: 'Related Video 2',
		thumbnails: [
			{
				url: 'https://example.com/thumbs/related2_low.jpg',
				height: 94,
				width: 168,
				estimatedResolutionLevel: 'LOW'
			},
			{
				url: 'https://example.com/thumbs/related2_medium.jpg',
				height: 188,
				width: 336,
				estimatedResolutionLevel: 'MEDIUM'
			}
		],
		streamType: 'VIDEO_STREAM',
		uploaderName: 'Related Channel 2',
		textualUploadDate: '2 years ago',
		viewCount: 32000000,
		duration: 850,
		uploaderUrl: 'https://example.com/channel/related2',
		uploaderAvatars: [],
		uploaderSubscriberCount: 0,
		shortFormContent: false	
	},	
	{
		...mockRelatedStream,
		id: 'related-stream-3',
		url: 'https://example.com/watch?v=related3',
		name: 'Related Video 3',
		thumbnails: [
			{
				url: 'https://example.com/thumbs/related3_low.jpg',
				height: 94,
				width: 168,
				estimatedResolutionLevel: 'LOW'
			},
			{
				url: 'https://example.com/thumbs/related3_medium.jpg',
				height: 188,
				width: 336,
				estimatedResolutionLevel: 'MEDIUM'
			}
		],
		streamType: 'VIDEO_STREAM',
		uploaderName: 'Related Channel 3',
		textualUploadDate: '1 year ago',
		viewCount: 16000000,
		duration: 720,
		uploaderUrl: 'https://example.com/channel/related3',
		uploaderAvatars: [],
		uploaderSubscriberCount: 0,
		shortFormContent: false
	}
];

export const mockRelatedVideoStreamArrayResponse = mockRelatedStreams;

export const mockRelatedStreamObjectResponse = {
	streams: mockRelatedStreams,
	videoId: 'test-video-id'
};

// =============================================================================
// Search Result Fixtures
// =============================================================================

export const mockSearchResult: SearchResult = [
	{
		id: 'video-1',
		url: 'https://youtube.com/watch?v=video-1',
		name: 'Test Video 1',
		streamDate: '2024-01-15T10:00:00Z',
		thumbnails: [
			{
				url: 'https://example.com/thumb1.jpg',
				height: 720,
				width: 1280,
				estimatedResolutionLevel: 'HIGH'
			}
		],
		textualUploadDate: '1 week ago',
		duration: 300,
		description: {
			content: 'Test description 1',
			type: 0
		},
		viewCount: 100000,
		likeCount: 5000,
		dislikeCount: 100,
		uploaderName: 'Test Channel 1',
		uploaderAvatars: [
			{
				url: 'https://example.com/avatar1.jpg',
				height: 48,
				width: 48,
				estimatedResolutionLevel: 'LOW'
			}
		],
		uploaderSubscriberCount: 500000,
		videoStreams: [],
		audioStreams: [],
		videoOnlyStreams: [],
		relatedItems: [],
		subtitles: [],
		category: 'Entertainment',
		streamSegments: [],
		shortFormContent: false
	},
	{
		id: 'video-2',
		url: 'https://youtube.com/watch?v=video-2',
		name: 'Test Video 2',
		streamDate: '2024-01-14T15:30:00Z',
		thumbnails: [
			{
				url: 'https://example.com/thumb2.jpg',
				height: 360,
				width: 640,
				estimatedResolutionLevel: 'MEDIUM'
			}
		],
		textualUploadDate: '2 weeks ago',
		duration: 600,
		description: {
			content: 'Test description 2',
			type: 0
		},
		viewCount: 50000,
		likeCount: 2000,
		dislikeCount: 50,
		uploaderName: 'Test Channel 2',
		uploaderAvatars: [],
		uploaderSubscriberCount: 100000,
		videoStreams: [],
		audioStreams: [],
		videoOnlyStreams: [],
		relatedItems: [],
		subtitles: [],
		category: 'Education',
		streamSegments: [],
		shortFormContent: false
	}
];

export const mockEmptySearchResult: SearchResult = [];

// =============================================================================
// Response Wrappers (for different API response formats)
// =============================================================================

export const mockVideoStreamsArrayResponse = mockVideoStreams;
export const mockVideoStreamsObjectResponse = {
	streams: mockVideoStreams,
	videoId: 'test-video-id'
};

export const mockAudioStreamsArrayResponse = mockAudioStreams;
export const mockAudioStreamsObjectResponse = {
	streams: mockAudioStreams,
	videoId: 'test-video-id'
};

export const mockSubtitlesArrayResponse = mockSubtitles;
export const mockSubtitlesObjectResponse = {
	subtitles: mockSubtitles,
	videoId: 'test-video-id'
};