/**
 * Mock Subtitle Data Fixtures
 * 
 * Reusable test data for subtitle selection tests
 */

import type { Subtitle } from '$lib/types';

/**
 * Creates a mock subtitle
 */
export function createMockSubtitle(overrides: Partial<Subtitle> = {}): Subtitle {
	return {
		id: 'en-001',
		url: 'https://example.com/subtitles/en.vtt',
		format: 'vtt',
		locale: 'en',
		displayLanguageName: 'English',
		languageTag: 'en',
		autogenerated: false,
		...overrides
	} as Subtitle;
}

/**
 * Creates a set of subtitles with different languages
 */
export function createMockMultiLanguageSubtitles(): Subtitle[] {
	return [
		createMockSubtitle({
			id: 'en-001',
			locale: 'en',
			languageTag: 'en',
			displayLanguageName: 'English',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'es-001',
			locale: 'es',
			languageTag: 'es',
			displayLanguageName: 'Spanish',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'fr-001',
			locale: 'fr',
			languageTag: 'fr',
			displayLanguageName: 'French',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'de-001',
			locale: 'de',
			languageTag: 'de',
			displayLanguageName: 'German',
			format: 'vtt',
			autogenerated: false
		})
	];
}

/**
 * Creates subtitles with both manual and auto-generated versions
 */
export function createMockSubtitlesWithAutoGenerated(): Subtitle[] {
	return [
		// English - manual
		createMockSubtitle({
			id: 'en-manual',
			locale: 'en',
			languageTag: 'en',
			displayLanguageName: 'English',
			format: 'vtt',
			autogenerated: false
		}),
		// English - auto-generated
		createMockSubtitle({
			id: 'en-auto',
			locale: 'en',
			languageTag: 'en',
			displayLanguageName: 'English (auto-generated)',
			format: 'vtt',
			autogenerated: true
		}),
		// Spanish - manual
		createMockSubtitle({
			id: 'es-manual',
			locale: 'es',
			languageTag: 'es',
			displayLanguageName: 'Spanish',
			format: 'vtt',
			autogenerated: false
		}),
		// Spanish - auto-generated
		createMockSubtitle({
			id: 'es-auto',
			locale: 'es',
			languageTag: 'es',
			displayLanguageName: 'Spanish (auto-generated)',
			format: 'vtt',
			autogenerated: true
		})
	];
}

/**
 * Creates subtitles in different formats
 */
export function createMockSubtitlesWithDifferentFormats(): Subtitle[] {
	return [
		createMockSubtitle({
			id: 'en-vtt',
			locale: 'en',
			displayLanguageName: 'English',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'en-srv3',
			locale: 'en',
			displayLanguageName: 'English',
			format: 'srv3',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'es-ttml',
			locale: 'es',
			displayLanguageName: 'Spanish',
			format: 'ttml',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'fr-srv1',
			locale: 'fr',
			displayLanguageName: 'French',
			format: 'srv1',
			autogenerated: false
		})
	];
}

/**
 * Creates duplicate subtitles for the same language
 */
export function createMockDuplicateSubtitles(): Subtitle[] {
	return [
		// First English subtitle - manual
		createMockSubtitle({
			id: 'en-001',
			locale: 'en',
			displayLanguageName: 'English',
			format: 'vtt',
			autogenerated: false
		}),
		// Second English subtitle - auto
		createMockSubtitle({
			id: 'en-002',
			locale: 'en',
			displayLanguageName: 'English (auto)',
			format: 'vtt',
			autogenerated: true
		}),
		// Third English subtitle - manual (different ID)
		createMockSubtitle({
			id: 'en-003',
			locale: 'en',
			displayLanguageName: 'English (CC)',
			format: 'vtt',
			autogenerated: false
		})
	];
}

/**
 * Creates subtitles with regional variants
 */
export function createMockSubtitlesWithRegionalVariants(): Subtitle[] {
	return [
		createMockSubtitle({
			id: 'en-US',
			locale: 'en-US',
			languageTag: 'en-US',
			displayLanguageName: 'English (United States)',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'en-GB',
			locale: 'en-GB',
			languageTag: 'en-GB',
			displayLanguageName: 'English (United Kingdom)',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'es-419',
			locale: 'es-419',
			languageTag: 'es-419',
			displayLanguageName: 'Spanish (Latin America)',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'es-ES',
			locale: 'es-ES',
			languageTag: 'es-ES',
			displayLanguageName: 'Spanish (Spain)',
			format: 'vtt',
			autogenerated: false
		})
	];
}

/**
 * Creates subtitles with missing or undefined fields
 */
export function createMockSubtitlesWithMissingFields(): Subtitle[] {
	return [
		// Missing locale, only languageTag
		createMockSubtitle({
			id: 'en-001',
			locale: undefined as any,
			languageTag: 'en',
			displayLanguageName: 'English',
			format: 'vtt',
			autogenerated: false
		}),
		// Missing languageTag, only locale
		createMockSubtitle({
			id: 'es-001',
			locale: 'es',
			languageTag: undefined as any,
			displayLanguageName: 'Spanish',
			format: 'vtt',
			autogenerated: false
		}),
		// Missing format
		createMockSubtitle({
			id: 'fr-001',
			locale: 'fr',
			languageTag: 'fr',
			displayLanguageName: 'French',
			format: undefined as any,
			autogenerated: false
		})
	];
}

/**
 * Creates subtitles with original/undefined language
 */
export function createMockSubtitlesWithOriginalLanguage(): Subtitle[] {
	return [
		createMockSubtitle({
			id: 'original',
			locale: 'und',
			languageTag: 'und',
			displayLanguageName: 'Original',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'en-001',
			locale: 'en',
			languageTag: 'en',
			displayLanguageName: 'English',
			format: 'vtt',
			autogenerated: false
		}),
		createMockSubtitle({
			id: 'es-001',
			locale: 'es',
			languageTag: 'es',
			displayLanguageName: 'Spanish',
			format: 'vtt',
			autogenerated: false
		})
	];
}