/**
 * Test Fixtures: VideoPlayer Component
 * 
 * Mock data for testing VideoPlayer component functionality
 */

import type { VideoPlayerConfig } from '$lib/adapters/types';

export const mockVideoStream = {
	url: 'https://example.com/video.mp4',
	codec: 'avc1.42E01E',
	mimeType: 'video/mp4',
	bandwidth: 5000000,
	width: 1920,
	height: 1080,
	frameRate: 30,
	format: 'MPEG_4',
	initStart: 0,
	initEnd: 740,
	indexStart: 741,
	indexEnd: 1200
};

export const mockVideoStream720p = {
	url: 'https://example.com/video-720p.mp4',
	codec: 'avc1.42E01E',
	mimeType: 'video/mp4',
	bandwidth: 2500000,
	width: 1280,
	height: 720,
	frameRate: 30,
	format: 'MPEG_4',
	initStart: 0,
	initEnd: 740,
	indexStart: 741,
	indexEnd: 1200
};

export const mockAudioStream = {
	url: 'https://example.com/audio.m4a',
	codec: 'mp4a.40.2',
	mimeType: 'audio/mp4',
	bandwidth: 128000,
	sampleRate: 48000,
	channels: 2,
	format: 'M4A',
	language: 'en',
	languageName: 'English',
	initStart: 0,
	initEnd: 648,
	indexStart: 649,
	indexEnd: 1100
};

export const mockAudioStreamSpanish = {
	url: 'https://example.com/audio-es.m4a',
	codec: 'mp4a.40.2',
	mimeType: 'audio/mp4',
	bandwidth: 128000,
	sampleRate: 48000,
	channels: 2,
	format: 'M4A',
	language: 'es',
	languageName: 'Spanish',
	initStart: 0,
	initEnd: 648,
	indexStart: 649,
	indexEnd: 1100
};

export const mockSubtitleStream = {
	url: 'https://example.com/subtitles-en.vtt',
	language: 'en',
	languageName: 'English',
	format: 'vtt',
	mimeType: 'text/vtt',
	kind: 'subtitles' as const,
	isAutoGenerated: false
};

export const mockSubtitleStreamFrench = {
	url: 'https://example.com/subtitles-fr.vtt',
	language: 'fr',
	languageName: 'French',
	format: 'vtt',
	mimeType: 'text/vtt',
	kind: 'subtitles' as const,
	isAutoGenerated: false
};

export const mockPlayerConfig: VideoPlayerConfig = {
	videoStream: [mockVideoStream, mockVideoStream720p],
	audioStream: [mockAudioStream, mockAudioStreamSpanish],
	subtitleStream: [mockSubtitleStream, mockSubtitleStreamFrench],
	duration: 180,
	poster: 'https://example.com/poster.jpg'
};

export const mockPlayerConfigVideoOnly: VideoPlayerConfig = {
	videoStream: [mockVideoStream],
	audioStream: null,
	subtitleStream: null,
	duration: 120,
	poster: 'https://example.com/poster-video-only.jpg'
};

export const mockPlayerConfigAudioOnly: VideoPlayerConfig = {
	videoStream: null,
	audioStream: [mockAudioStream],
	subtitleStream: null,
	duration: 90,
	poster: 'https://example.com/poster-audio-only.jpg'
};

export const mockPlayerConfigNoStreams: VideoPlayerConfig = {
	videoStream: null,
	audioStream: null,
	subtitleStream: null,
	duration: 0,
	poster: 'https://example.com/poster-no-streams.jpg'
};

export const mockPlayerConfigSingleQuality: VideoPlayerConfig = {
	videoStream: [mockVideoStream],
	audioStream: [mockAudioStream],
	subtitleStream: null,
	duration: 150,
	poster: 'https://example.com/poster-single.jpg'
};

export const mockPlayerConfigMultipleQualities: VideoPlayerConfig = {
	videoStream: [
		mockVideoStream,
		mockVideoStream720p,
		{
			...mockVideoStream,
			width: 854,
			height: 480,
			bandwidth: 1000000,
			url: 'https://example.com/video-480p.mp4'
		}
	],
	audioStream: [mockAudioStream],
	subtitleStream: [mockSubtitleStream],
	duration: 200,
	poster: 'https://example.com/poster-multi.jpg'
};

export const mockPlayerConfigVerticalVideo: VideoPlayerConfig = {
	videoStream: [{
		...mockVideoStream,
		width: 1080,
		height: 1920
	}],
	audioStream: [mockAudioStream],
	subtitleStream: null,
	duration: 60,
	poster: 'https://example.com/poster-vertical.jpg'
};

export const mockPlayerConfig4K: VideoPlayerConfig = {
	videoStream: [{
		...mockVideoStream,
		width: 3840,
		height: 2160,
		bandwidth: 15000000,
		url: 'https://example.com/video-4k.mp4'
	}],
	audioStream: [mockAudioStream],
	subtitleStream: null,
	duration: 240,
	poster: 'https://example.com/poster-4k.jpg'
};

// Shaka Player error codes
export const SHAKA_ERROR_CODES = {
	NETWORK_ERROR: 1001,
	FORMAT_NOT_SUPPORTED: 3016,
	STREAM_EXPIRED: 4012,
	MANIFEST_ERROR: 4006
};

// Mock Shaka error objects
export const createMockShakaError = (code: number, message: string) => ({
	code,
	message,
	severity: 2,
	category: 1,
	data: []
});

export const mockNetworkError = createMockShakaError(
	SHAKA_ERROR_CODES.NETWORK_ERROR,
	'Network error occurred'
);

export const mockFormatError = createMockShakaError(
	SHAKA_ERROR_CODES.FORMAT_NOT_SUPPORTED,
	'Video format not supported'
);

export const mockStreamExpiredError = createMockShakaError(
	SHAKA_ERROR_CODES.STREAM_EXPIRED,
	'Stream has expired'
);

export const mockManifestError = createMockShakaError(
	SHAKA_ERROR_CODES.MANIFEST_ERROR,
	'Unable to load manifest'
);